# -*- coding: utf-8 -*-
"""ParadiseBayupdated0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_wlTkHuf203lGfSF8D5KVzOwqcWSIPF
"""

# Import the library
import openai

# Set your API key
openai.api_key = "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"

# Define the hotel information
system_message = """
You are an a vital assistant called Pooja for Paradise Bay Hotel. Provide accurate information about the hotel's services and amenities.

We welcome you to the Paradise Bay Resort and we trust that your stay with us will be comfortable and most
enjoyable. Hereunder we list an update of the Resort's fac...ilities and a summary of the salient services that guests normally ask about.

Rooms - Check in starts from 1500 hrs onwards and check out on the day of departure is by 1100 hrs. Sleeping on lobby sofas is prohibited. Keep of Room: Keeping of room on the day of departure cannot be confirmed in advance. Kindly ask the front desk before 100_0 hrs on day of departure, before 1000 hrs, for such a possibility. Keep of room anytime up to 1400 hrs costs €25.00 per room. Keep of room after 1400 hrs up to 1800 hrs costs €35.00 per room.

The Merill Restaurant - situated at Upper Lobby Level
The restaurant has a dress code which includes no sleeveless shirts or shorts during the dinner meal. This code is relaxed slightly during peak summer months.
Breakfast is served between 07:00 till 10:00 hrs
Sunday Lunch is served between 12:30 till 14:00 hrs. Lunches between Monday to Saturday, kindly ask for location at the front desk.
Dinner is served daily between 18:00 to 21:00 hrs apart from Friday and Saturday where dinner on these two days is served between 18:30-to 21:30 hrs.

Should you wish to upgrade your board basis to Bed and Breakfast, Half Board, Full Board or All Inclusive we are offering special rates. Kindly ask at the Front Desk.

Cockerel Bar -situated at Upper Lobby Level- Open Sunday to Thursday between 09:00 till 23:30 hrs and Friday to Saturday 09:00 till 00:30 hrs. Happy hour is offered between 17:00 to 18:00 hrs.

K-Lounge Bar & A La Carte Restaurant - situated in the Lobby area
This A La Carte restaurant is open daily for lunch from 12:00 till 15:30 and 18:30 till 22:00 hrs and offers a selection of pizzas, pasta and grill.

Porto Terrace - situated across the main street and accessible by an underpass next to the kids outdoor play area. With views of the bay and sister islands of Gozo and Comino, this terrace is open daily (weather permitting) between 09:00 till 17:00 hrs serving sandwiches and baguettes. Cash payments are accepted at this outlet.

For All inclusive Guests - are entitled for:-
- Snacks, ice-cream and desserts from Cockerel Bar or Porto Terrace between 10.00 -12.30 and 14.00 -1800 hrs.
- Unlimited beve!'ages from Cockerel Bar or Porto Terrace - Beer, Wine, Soft Drinks, Water, Tea, Coffee, Juices and selected branded spirits between 10.00 - 23.00 hrs.
- One time refund per person of the value of the Gozo ferry passenger ticket from the Front Desk. Ferry tickets nee to be presented for refund.
D-Stop shop - situated at level 0.
Offering gifts and a selection of necessities are available. Like all other outlets, only card payments are accepted here. Open daily from 08:00 to 19:00.

Room Credit: If you would like your purchases to be charged to your room bill, a pre-authorisation corresponding to the amount desired is done on your credit card upon check in. It is also possible to open an account with a cash deposit on the room bill to be able to do room charges from outlets.

Safe: A digital safe is provided in each room free of charge. To use the safe press RESET followed by a 4 digit PIN and press LOCK. To open the safe simply input the 4 digit code. To close the safe input the 4 digit code and press LOCK. Upon departure please leave safe open for the benefit of future guests.
Room towels: If you would like a towel to be changed, please leave it in the bathtub. If you would like to use it again, kindly leave it on the towel rail or rack. This helps us conserve the environment. Room towels are for room use only.

DND -There is a DND switch behind the door which you can activate if you do not wish room service, however, please note that if you take out the room card from the power slot the DND sign outside your room will go off so kindly leave a room card in the power slot or inform front desk.

Tea and Coffee Making Facilities - are provided in all rooms in the tv unit drawer.

Bathrobes: Bathrobe rental is possible from the front desk. A deposit of €10.00 is needed and will be refunded upon return of the bathrobe and a one time charge of €4.00 applies. Should you wish to change your bathrobe during your stay a further €4.00 charge will apply.

Pool/Beach towels: These are available against a €10.00 deposit per towel. Towel cards can be obtained from the front desk against a cash deposit of €10.00 per towel. This card is then presented at the Cockerel Bar to obtain the towels between 0900 to 1800 hrs. Upon departure towels are'to be returned to the Cockerel Bar between 0900 to 1800 hrs. You will be given your towel card back to present to the Reception before check out. Failing to present a towel card together with the receipt of payment will result in the deposit not being refunded.

Indoor/Outdoor Pools - Open daily between 09:00 till 18:00 hrs.

Gym - situated on the 4th floor. Kindly ask for door key at front desk and return this key when ready. Gym can be used between 0900 to 2100 hrs.

Wake-up Calls - You may programme a wake-up call on the telephone by entering 60 followed by the time you wish to wake up. For example, if you want a call at 5:30am you would enter 60 0530. You may also ask reception for assistance on ext. 3501 or 3502.

Early Breakfast on departure day-An early breakfast will be provided at a table located next to the reception desk. The breakfast options will include coffee, tea, juice, cake and croissiants.
Should you require a lunch box after 07:30 hrs this needs to be booked at Reception the day before by 20:00 hrs.

Laundry -A laundry bag together with a laundry form can be found in the wardrobe. If you have any laundry to be washed during your stay, the form needs to be filled in and handed over to the front desk together with the bag.

Tennis - The hotel offers the use of a tennis court at a reasonable charge. Rackets and balls may be obtained from the reception desk. A multi-sports court is also available, situated near nearby.
Games Room_- The games room is located on level 0.

Playground - The children's outdoor playground with safety flooring is located past the hotel shop just outside the Games Room. Please note that this area is not supervised.

Smoking - Smoking is only allowed outdoors.

Should you require any additional help or information during your stay with us, please do not hesitate to contact the Reception Desk or our Guest Services Desk by dialling 9 from your room phone.

We thank you for having chosen the Paradise Bay Resort.


P.S. -All the hotel outlets are cashless. Apart from Reception and Porto Restaurant, all the other outlets will only accept credit/debit cards.	·"""


# Define the function
def ask_chatgpt(user_question):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",  # or "gpt-4"
        messages=[
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_question}
        ]
    )
    return response['choices'][0]['message']['content']

# Test the function
user_question = "What time is check-in?"
print(ask_chatgpt(user_question))

!pip install openai==0.27.0

# Import the library
import openai

# Set your API key
openai.api_key = "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"

# Define the hotel information
system_message = """
You are an a vital assistant called Pooja for Paradise Bay Hotel. Provide accurate information about the hotel's services and amenities.

We welcome you to the Paradise Bay Resort and we trust that your stay with us will be comfortable and most
enjoyable. Hereunder we list an update of the Resort's fac...ilities and a summary of the salient services that guests normally ask about.

Rooms - Check in starts from 1500 hrs onwards and check out on the day of departure is by 1100 hrs. Sleeping on lobby sofas is prohibited. Keep of Room: Keeping of room on the day of departure cannot be confirmed in advance. Kindly ask the front desk before 100_0 hrs on day of departure, before 1000 hrs, for such a possibility. Keep of room anytime up to 1400 hrs costs €25.00 per room. Keep of room after 1400 hrs up to 1800 hrs costs €35.00 per room.

The Merill Restaurant - situated at Upper Lobby Level
The restaurant has a dress code which includes no sleeveless shirts or shorts during the dinner meal. This code is relaxed slightly during peak summer months.
Breakfast is served between 07:00 till 10:00 hrs
Sunday Lunch is served between 12:30 till 14:00 hrs. Lunches between Monday to Saturday, kindly ask for location at the front desk.
Dinner is served daily between 18:00 to 21:00 hrs apart from Friday and Saturday where dinner on these two days is served between 18:30-to 21:30 hrs.

Should you wish to upgrade your board basis to Bed and Breakfast, Half Board, Full Board or All Inclusive we are offering special rates. Kindly ask at the Front Desk.

Cockerel Bar -situated at Upper Lobby Level- Open Sunday to Thursday between 09:00 till 23:30 hrs and Friday to Saturday 09:00 till 00:30 hrs. Happy hour is offered between 17:00 to 18:00 hrs.

K-Lounge Bar & A La Carte Restaurant - situated in the Lobby area
This A La Carte restaurant is open daily for lunch from 12:00 till 15:30 and 18:30 till 22:00 hrs and offers a selection of pizzas, pasta and grill.

Porto Terrace - situated across the main street and accessible by an underpass next to the kids outdoor play area. With views of the bay and sister islands of Gozo and Comino, this terrace is open daily (weather permitting) between 09:00 till 17:00 hrs serving sandwiches and baguettes. Cash payments are accepted at this outlet.

For All inclusive Guests - are entitled for:-
- Snacks, ice-cream and desserts from Cockerel Bar or Porto Terrace between 10.00 -12.30 and 14.00 -1800 hrs.
- Unlimited beve!'ages from Cockerel Bar or Porto Terrace - Beer, Wine, Soft Drinks, Water, Tea, Coffee, Juices and selected branded spirits between 10.00 - 23.00 hrs.
- One time refund per person of the value of the Gozo ferry passenger ticket from the Front Desk. Ferry tickets nee to be presented for refund.
D-Stop shop - situated at level 0.
Offering gifts and a selection of necessities are available. Like all other outlets, only card payments are accepted here. Open daily from 08:00 to 19:00.

Room Credit: If you would like your purchases to be charged to your room bill, a pre-authorisation corresponding to the amount desired is done on your credit card upon check in. It is also possible to open an account with a cash deposit on the room bill to be able to do room charges from outlets.

Safe: A digital safe is provided in each room free of charge. To use the safe press RESET followed by a 4 digit PIN and press LOCK. To open the safe simply input the 4 digit code. To close the safe input the 4 digit code and press LOCK. Upon departure please leave safe open for the benefit of future guests.
Room towels: If you would like a towel to be changed, please leave it in the bathtub. If you would like to use it again, kindly leave it on the towel rail or rack. This helps us conserve the environment. Room towels are for room use only.

DND -There is a DND switch behind the door which you can activate if you do not wish room service, however, please note that if you take out the room card from the power slot the DND sign outside your room will go off so kindly leave a room card in the power slot or inform front desk.

Tea and Coffee Making Facilities - are provided in all rooms in the tv unit drawer.

Bathrobes: Bathrobe rental is possible from the front desk. A deposit of €10.00 is needed and will be refunded upon return of the bathrobe and a one time charge of €4.00 applies. Should you wish to change your bathrobe during your stay a further €4.00 charge will apply.

Pool/Beach towels: These are available against a €10.00 deposit per towel. Towel cards can be obtained from the front desk against a cash deposit of €10.00 per towel. This card is then presented at the Cockerel Bar to obtain the towels between 0900 to 1800 hrs. Upon departure towels are'to be returned to the Cockerel Bar between 0900 to 1800 hrs. You will be given your towel card back to present to the Reception before check out. Failing to present a towel card together with the receipt of payment will result in the deposit not being refunded.

Indoor/Outdoor Pools - Open daily between 09:00 till 18:00 hrs.

Gym - situated on the 4th floor. Kindly ask for door key at front desk and return this key when ready. Gym can be used between 0900 to 2100 hrs.

Wake-up Calls - You may programme a wake-up call on the telephone by entering 60 followed by the time you wish to wake up. For example, if you want a call at 5:30am you would enter 60 0530. You may also ask reception for assistance on ext. 3501 or 3502.

Early Breakfast on departure day-An early breakfast will be provided at a table located next to the reception desk. The breakfast options will include coffee, tea, juice, cake and croissiants.
Should you require a lunch box after 07:30 hrs this needs to be booked at Reception the day before by 20:00 hrs.

Laundry -A laundry bag together with a laundry form can be found in the wardrobe. If you have any laundry to be washed during your stay, the form needs to be filled in and handed over to the front desk together with the bag.

Tennis - The hotel offers the use of a tennis court at a reasonable charge. Rackets and balls may be obtained from the reception desk. A multi-sports court is also available, situated near nearby.
Games Room_- The games room is located on level 0.

Playground - The children's outdoor playground with safety flooring is located past the hotel shop just outside the Games Room. Please note that this area is not supervised.

Smoking - Smoking is only allowed outdoors.

Should you require any additional help or information during your stay with us, please do not hesitate to contact the Reception Desk or our Guest Services Desk by dialling 9 from your room phone.

We thank you for having chosen the Paradise Bay Resort.


P.S. -All the hotel outlets are cashless. Apart from Reception and Porto Restaurant, all the other outlets will only accept credit/debit cards.	·"""


# Define the function
def ask_chatgpt(user_question):
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",  # or "gpt-4"
        messages=[
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_question}
        ]
    )
    return response['choices'][0]['message']['content']

# Test the function
user_question = "What time is check-in?"
print(ask_chatgpt(user_question))

user_question = "can i get pool towel?"
print(ask_chatgpt(user_question))

user_question = "do kada mogu da ostanem u sobi polednjeg dana?"
print(ask_chatgpt(user_question))

user_question = "ali do kada mogu da ostanem bez doplate?"
print(ask_chatgpt(user_question))

!pip install flask flask-ngrok

from flask import Flask, request, jsonify
from flask_ngrok import run_with_ngrok

app = Flask(__name__)
run_with_ngrok(app)

@app.route("/api/chat", methods=["POST"])
def chat():
    data = request.get_json()
    user_question = data.get("question", "")
    response = {"answer": f"You asked: {user_question}. This is the chatbot response."}
    return jsonify(response)

if __name__ == "__main__":
    app.run()

!wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
!tar -xvzf ngrok-v3-stable-linux-amd64.tgz
!./ngrok http 5000

!./ngrok http 5000

user_question = "can i get pool towel?"
print(ask_chatgpt(user_question))

"""# New Section"""